CREATE DATABASE ACTIVANTS_LMS_COUNSELLOR;

CREATE TABLE COUNSELLOR(
    COUNSELLOR_ID SERIAL PRIMARY KEY,
    COUNSELLOR_NAME VARCHAR(255),
    COUNSELLOR_AGE INTEGER
)

CREATE TABLE "T_USER"(
  "ID_USER" serial not null,
  "ID_USER_UUID" uuid DEFAULT uuid_generate_v4(),
  "TX_USER_NAME" VARCHAR(255) NOT NULL,
  "TX_USER_EMAIL" VARCHAR(255) NOT NULL UNIQUE,
  "TX_USER_PASSWORD" VARCHAR(255) NOT NULL,
  "TX_VERIFICATION_STATUS" BIT NOT NULL,
  "DT_DATE_CREATED" timestamp with time zone NOT NULL,
  "IN_ACTIVE" BIT NOT NULL,
  PRIMARY KEY("ID_USER")
);

insert into "T_USER" ("TX_USER_NAME","TX_USER_EMAIL",
"TX_USER_PASSWORD","TX_VERIFICATION_STATUS","DT_DATE_CREATED","IN_ACTIVE") 
values ('indra','indra@gmail.com','123123','0','17-09-2020','1')
